### ISSUE TITLE
Failed to synchronise

### ISSUE THREAD

**Issue by gebteus** [Azure/blobxfer#1] opened 2016-09-01 08:06 UTC
Failed to synchronise an empty local folder with an empty blob container when using --delete.
This command will throw an exception about that could not authenticate to the server. The probable reason is the parameter "include" in the request to the server.

_upd._
**directory /blobtest is empty and container is not empty.**
```sh
blobxfer ACCOUNT test /blobtest --storageaccountkey KEY --delete

script start time: 2016-09-02 11:37:08
creating container, if needed: test
deleting 37 remote blobs
deletion complete.
detected no transfer actions needed to be taken, exiting...
```

**directory /blobtest is empty and container is empty.**
```sh
blobxfer ACCOUNT test /blobtest --storageaccountkey KEY --delete

script start time: 2016-09-02 11:37:12
Traceback (most recent call last):
  File "/usr/bin/blobxfer", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/blobxfer.py", line 2389, in main
    blob_service[0], args, metadata=False)
  File "/usr/lib/python2.7/site-packages/blobxfer.py", line 1605, in get_blob_listing
    container_name=args.container, marker=marker, include=incl)
  File "/usr/lib/python2.7/site-packages/blobxfer.py", line 1418, in azure_request
    return req(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/azure/storage/blob/baseblobservice.py", line 1177, in list_blobs
    resp = self._list_blobs(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/azure/storage/blob/baseblobservice.py", line 1247, in _list_blobs
    response = self._perform_request(request)
  File "/usr/lib/python2.7/site-packages/azure/storage/storageclient.py", line 195, in _perform_request
    _storage_error_handler(HTTPError(response.status, response.message, response.headers, response.body))
  File "/usr/lib/python2.7/site-packages/azure/storage/_serialization.py", line 125, in _storage_error_handler
    return _general_error_handler(http_error)
  File "/usr/lib/python2.7/site-packages/azure/storage/_error.py", line 74, in _general_error_handler
    raise AzureHttpError(message, http_error.status)
azure.common.AzureHttpError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:7779c4fa-0001-0115-02f5-04dd08000000
Time:2016-09-02T08:37:11.7990970Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request '+JjRFkacbfHXhzsvLYhR2Jci5nty2b8Xtd4hwT1TVVc=' is not the same as any computed signature. Server used following string to sign: 'GET

x-ms-client-request-id:71b1790e-70e8-11e6-9ee8-001c42abe891
x-ms-date:Fri, 02 Sep 2016 08:37:12 GMT
x-ms-version:2015-07-08
/ACCOUNT/test
comp:list
include:
restype:container'.</AuthenticationErrorDetail></Error>
```

**Comment by alfpark** [comment] 2016-09-01 16:17
Can you please provide the error output? Please redact anything sensitive in the log.

**Comment by gebteus** [comment] 2016-09-02 19:19
Okay

**Comment by gebteus** [comment] 2016-09-02 19:23
Okay. Added.

**Comment by alfpark** [comment] 2016-09-02 20:14
Thanks @gebteus for the bug report. The issue is fixed and has been merged to master. It will be rolled into the next release.

**Closed** 2016-09-03 10:18 UTC
Labels: bug
