### ISSUE TITLE
413 Client Error: The request body is too large and exceeds the maximum permissible limit

### ISSUE THREAD

**Issue by mlin** [Azure/blobxfer#6] opened 2016-10-08 04:19 UTC
Following up from #5 
I am now running the docker image to upload a 191GB file, and hitting this after about 30 minutes (XXX = my redactions):

```
-rw-r--r-- 1 root root 191G Oct  8 01:39 NA12892_recompressed.bam
Image Repo	alfpark/blobxfer
Image Tag	latest
Image Size	89M
Image ID	sha256:4e0dbe3348a186e8e716388bc2f8d4de80e7893d578a5750e7022d67b37477f1
Last Updated	2016-10-03T15:54:00.876894577Z (4d 9h ago)
Registry	registry-1.docker.io
=====================================
 azure blobxfer parameters [v0.11.5]
=====================================
             platform: Linux-3.13.0-96-generic-x86_64-with
   python interpreter: CPython 3.5.2
     package versions: az.common=1.1.4 az.sml=0.20.5 az.stor=0.33.0 crypt=1.5.2 req=2.11.1
      subscription id: None
      management cert: None
   transfer direction: local->Azure
       local resource: /data/NA12892_recompressed.bam
      include pattern: None
      remote resource: None
   max num of workers: 12
              timeout: None
      storage account: XXX
              use SAS: True
  upload as page blob: False
  auto vhd->page blob: False
 upload to file share: False
 container/share name: XXX
  container/share URI: XXX
    compute block MD5: False
     compute file MD5: False
    skip on MD5 match: True
   chunk size (bytes): 4194304
     create container: False
  keep mismatched MD5: False
     recursive if dir: True
component strip on up: 1
        remote delete: False
           collate to: disabled
      local overwrite: True
      encryption mode: disabled
         RSA key file: disabled
         RSA key type: disabled
=======================================
script start time: 2016-10-08 01:39:37
detected 0 empty files to upload
performing 48889 put blocks/blobs and 1 put block lists
spawning 12 worker threads
  File "/usr/lib/python3.5/site-packages/blobxfer.py", line 941, in run
    offset, bytestoxfer, encparam, flock, filedesc)
  File "/usr/lib/python3.5/site-packages/blobxfer.py", line 1095, in put_storage_data
    timeout=self.args.timeout)
  File "/usr/lib/python3.5/site-packages/blobxfer.py", line 1418, in azure_request
    return req(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/blobxfer.py", line 776, in put_block
    response.raise_for_status()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 413 Client Error: The request body is too large and exceeds the maximum permissible limit. for url: XXX
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/blobxfer.py", line 941, in run
    offset, bytestoxfer, encparam, flock, filedesc)
  File "/usr/lib/python3.5/site-packages/blobxfer.py", line 1095, in put_storage_data
    timeout=self.args.timeout)
  File "/usr/lib/python3.5/site-packages/blobxfer.py", line 1418, in azure_request
    return req(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/blobxfer.py", line 776, in put_block
    response.raise_for_status()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 413 Client Error: The request body is too large and exceeds the maximum permissible limit. for url: XXX
```

**Comment by alfpark** [comment] 2016-10-09 18:10
@mlin We've observed this before and have been unable to root cause the issue; see https://github.com/Azure/azure-batch-samples/issues/106. There is a workaround, please set `--chunksizebytes 4194300` (or 4194296) and please let me know if you still see this issue. Because you are very close to the maximum blob size limit, this will impact how big of a file you can upload.

**Comment by mlin** [comment] 2016-10-10 05:44
@alfpark Ok, thanks for the info. I'll leave it to you whether to keep this github issue open. In the course of pursuing multiple troubleshooting steps in parallel, I applied some tricks to reduce the size of the files I'm uploading by about 50%, and have now transferred them successfully (without changing chunksizebytes, and without encountering #5 using the docker image). Thanks again.

**Comment by alfpark** [comment] 2016-10-10 22:29
@mlin Thanks for the update. Will close this issue.

**Closed by alfpark** 2016-10-10 22:29 UTC
